spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jeweller_shop
    username: postgres
    password: Yan9100fg5
    driver-class-name: org.postgresql.Driver
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=10m, recordStats
    cache-names: "userProfile, allUsers, userById, 
    allFavours, favourById, userOrders, userOrder, allOrders"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8089
  # prometeus
management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info,metrics"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true